Repository WorldWindEarth/WorldWindJava, pull requests merged in 2019-04, with the labels that each got.

#12 Fix issue if no positions in PhaseLine determineLabelPositions method.
  src/gov/nasa/worldwind/symbology/milstd2525/graphics/lines/PhaseLine.java
Labels: bug

#14 Determinant fix
  src/gov/nasa/worldwind/geom/Matrix.java
  test/gov/nasa/worldwind/geom/MatrixTest.java
Labels: bug

#18 Correct test for DTED file extension
  src/gov/nasa/worldwindx/examples/dataimport/InstallDTED.java
Labels: enhancement

#19 Fixed AVKey misspelling.
  src/gov/nasa/worldwind/avlist/AVKey.java
Labels: task

#20 Correct typographical error in DTED Level 2 RPF
  src/gov/nasa/worldwind/formats/rpf/RPFDataSeries.java
Labels: bug

#26 Updated IntelliJ IDE settings
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/runConfigurations/ApplicationTemplate.xml
  .idea/runConfigurations/KMLViewer.xml
  .idea/runConfigurations/WMSLayerManager.xml
  WorldWind.iml
Labels: task

#28 Added multiple JDKs to the Travis-CI build
  .travis.yml
Labels: enhancement

#34 Updated .travis.yml to force the use of Ant over Gradle
  .travis.yml
Labels: enhancement

#30 Initial gradle build configuration
  .gitignore
  build.gradle
  settings.gradle
Labels: enhancement

#39 PointPlacemark & PointPlacemarkAttributes Pitch
  src/gov/nasa/worldwind/render/PointPlacemark.java
Labels: bug

#40 Added SurfaceText rotation
  src/gov/nasa/worldwind/render/SurfaceText.java
  testFunctional/gov/nasa/worldwind/render/SurfaceTextTest.java
Labels: enhancement
