Repository WorldWindEarth/WorldWindJava, pull requests merged in 2019-06, with the labels that each got.

#49 Publish artifacts to Maven central
  .travis.yml
  build.gradle
Labels: task

#52 Restore possibility to tilt 2D globe
  src/config/worldwind.xml
  src/gov/nasa/worldwind/avlist/AVKey.java
  src/gov/nasa/worldwind/view/BasicViewPropertyLimits.java
Labels: enhancement

#54 Gdal no alpha band fix
  .nb-gradle-properties
  GDAL_README.txt
  logging.properties
  src/gov/nasa/worldwind/data/GDALDataRaster.java
  src/gov/nasa/worldwind/util/Logging.java
  src/gov/nasa/worldwind/util/MessageStrings.properties
  src/gov/nasa/worldwind/util/gdal/GDALUtils.java
Labels: bug

#56 Fixed null-Globe bug in FlyToOrbitViewAnimator.
  src/gov/nasa/worldwind/view/orbit/FlyToOrbitViewAnimator.java
Labels: bug
